#! /bin/sh
sxhkd -c /home/yutah/config/sxhkdrc

pgrep -x sxhkd > /dev/null || sxhkd &

xrdb .Xresources

#Autostart
#xrandr --auto --output DP-2 --mode 2560x1080 --left-of DP-1
#
#xrandr --output DP-2 --mode 3440x1440 --rate 100.00 --output DP-1 --mode 2560x1440 --r>
#xrandr --output DP-2 --mode  1720x1440  --output DP-1 --mode 2560x1440 --right-of DP-2
#xrandr --output DP-2 --mode 2560x1440 --rotate right --output DP-3 --mode 2560x1080 -->
xrandr --output DP-2 --mode 2560x1440 -r 59 --rotate right --output DP-3 --mode 2560x10>

#bspc monitor DP-1 -d I II III IV V VI VII VIII IX X
bspc monitor DP-3 -d IV V VI
bspc monitor DP-2 -d I II III

bspc config automatic_scheme spiral

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on