#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           10

#custom
bspc config top_padding	       0

bspc config focused_border_color \#69ffc8
bspc config normal_border_color \#990085

#custom

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius      	 60.0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#custom rules
bspc rule -a feh state=floating focus=off

#Autostart
picom &
feh --bg-fill --randomize $HOME/Pictures/bg/*

$HOME/.config/polybar/launch.sh
